import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-gray-900 text-white p-4 sticky top-0 z-50">
          <div className="max-w-7xl mx-auto flex items-center gap-6">
            <Link href="/" className="font-bold text-xl mr-4 text-blue-400">
              Deriva
            </Link>
            <Link href="/" className="hover:text-blue-300 transition-colors">
              Dashboard
            </Link>
            <Link href="/portfolio" className="hover:text-blue-300 transition-colors">
              Portfolio Risk
            </Link>
            <Link href="/trades" className="hover:text-blue-300 transition-colors">
              Trades Ledger
            </Link>
            <Link href="/options" className="hover:text-blue-300 transition-colors">
              Options Chain
            </Link>
          </div>
        </nav>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
